name: Package Application with Pyinstaller

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    if: github.repository_owner == 'LOLeoReal'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: 3.10
        
    - run: pip install pyinstaller
    - run: pyinstaller --onefile millionaire.py

    - uses: actions/upload-artifact@v2
      with:
        path: dist/millionaire.exe
